#  This file is used to initialize ElasticSearch with Data
from storage_client import ElasticBookStorage

# https://www.kaggle.com/ymaricar/cmu-book-summary-dataset

DATA = [
    {"title": "Elasticsearch: The Definitive Guide", "authors": ["clinton gormley", "zachary tong"],
     "summary": "A distibuted real-time search and analytics engine", "publish_date": "2015-02-07", "num_reviews": 20,
     "publisher": "oreilly"},
    {"title": "Taming Text: How to Find, Organize, and Manipulate It",
     "authors": ["grant ingersoll", "thomas morton", "drew farris"],
     "summary": "organize text using approaches such as full-text search, proper name recognition, clustering, tagging, information extraction, and summarization",
     "publish_date": "2013-01-24", "num_reviews": 12, "publisher": "manning"},
    {"title": "Elasticsearch in Action", "authors": ["radu gheorge", "matthew lee hinman", "roy russo"],
     "summary": "build scalable search applications using Elasticsearch without having to do complex low-level programming or understand advanced data science algorithms",
     "publish_date": "2015-12-03", "num_reviews": 18, "publisher": "manning"},
    {"title": "Solr in Action", "authors": ["trey grainger", "timothy potter"], "summary": "Comprehensive guide",
     "publish_date": "2015-12-03", "num_reviews": 18, "publisher": "manning"},
    {"title": "The Algorithmic Leader: How to Be Smart When Machines Are Smarter Than You", "authors": ["Mike Walsh"], "summary": "The Algorithmic Leader offers a hopeful and practical guide for leaders of all types, and organizations of all sizes, to survive and thrive in this era of unprecedented change. By applying Walsh's 10 core principles, readers will be able to design their own journey of personal transformation, harness the power of algorithms, and chart a clear path ahead--for their company, their team, and themselves",
     "publish_date": "2019-01-01", "num_reviews": 23, "publisher": "leader"},
    {"title": "Algorithms to Live By: The Computer Science of Human Decisions", "authors": ["Brian Christian","Tom Griffiths"], "summary": "explain how to have better hunches and when to leave things to chance, how to deal with overwhelming choices and how best to connect with others. From finding a spouse to finding a parking spot, from organizing one's inbox to understanding the workings of memory, Algorithms to Live By transforms the wisdom of computer science into strategies for human living",
     "publish_date": "2016-12-03", "num_reviews": 34, "publisher": "manning"},
    {"title": "Python Programming", "authors": ["John Zelle"], "summary": "Python Programming, Computer Science, Python Best practices",
     "publish_date": "2018-12-03", "num_reviews": 45, "publisher": "oreilly"},
    {"title": "Data Science for Business", "authors": ["JFoster Provost", "Tom Fawcett"],
     "summary": "Data Science for Business introduces the fundamental principles of data science, and walks you through the data-analytic thinking necessary for extracting useful knowledge and business value from the data you collect. This guide also helps you understand the many data-mining techniques in use today",
     "publish_date": "2015-11-23", "num_reviews": 45, "publisher": "oreilly"},
    {"title": "Network Security Through Data Analysis", "authors": ["Michael Collins"],
     "summary": 'process of collecting and organizing data, various tools for analysis, and several different analytic scenarios and techniques',
     "publish_date": "2019-12-03", "num_reviews": 55, "publisher": "oreilly"},
    {"title": "Data Mining with R", "authors": ["Luis Torgo"],
     "summary": 'Learning with Case Studies, Second Edition uses practical examples to illustrate the power of R and data mining',
     "publish_date": "2017-10-03", "num_reviews": 15, "publisher": "CRC Press"},
    {"title": "Data Analytics", "authors": ["Herbert Jones"],
     "summary": 'The Ultimate Guide to Big Data Analytics for Business, Data Mining Techniques, Data Collection, and Business Intelligence Concepts',
     "publish_date": "2018-04-12", "num_reviews": 35, "publisher": "CRC Press"},
    {"title": "Process Mining", "authors": ["Wil M. P. van der Aalst"],
     "summary": 'process optimization, data mining, data analysis methods, data mining techniques, big data analysis',
     "publish_date": "2016-10-03", "num_reviews": 45, "publisher": "Springer"},
    {"title": "Data Mining: The Textbook", "authors": ["Charu C. Aggarwal"],
     "summary": 'explores the different aspects of data mining from the fundamentals to the complex data types and their applications, capturing the wide diversity of problem domains for data mining issues',
     "publish_date": "2015-10-03", "num_reviews": 65, "publisher": "Springer"},
    {"title": "Principles of Data Mining", "authors": ["Max Bramer"],
     "summary": 'This book explains the principal techniques of data mining, for classification, association rule mining and clustering',
     "publish_date": "2018-10-03", "num_reviews": 45, "publisher": "Springer"},
    {"title": "The Elements of Statistical Learning", "authors": ["Trevor Hastie", "Robert Tibshirani", "Jerome Friedman"],
     "summary": 'The many topics include neural networks, support vector machines, classification trees and boosting. The first comprehensive treatment of this topic in any bookThis major new edition features many topics not covered in the original, including graphical models, random forests, ensemble methods, least angle regression & path algorithms for the lasso, non-negative matrix factorisation, and spectral clustering',
     "publish_date": "2018-10-03", "num_reviews": 45, "publisher": "Springer"},
    {"title": "Individual and Collective Graph Mining", "authors": ["Danai Koutra", "Christos Faloutsos"],
     "summary": 'This book presents scalable, principled discovery algorithms that combine globality with locality to make sense of one or more graphs, Graph Mining',
     "publish_date": "2016-10-03", "num_reviews": 45, "publisher": "Springer"},
    {"title": "Intelligent Speech Signal Processing", "authors": ["Nilanjan Dey"],
     "summary": ' utilization of speech analytics across several systems and real-world activities, including sharing data analytics, creating collaboration networks between several participants, and implementing video-conferencing in different application areas',
     "publish_date": "2018-10-03", "num_reviews": 45, "publisher": "CRC Press"},
    {"title": "Data Mining and Data Warehousing", "authors": ["Parteek Bhatia"],
     "summary": ' Important topics including information theory, decision tree, Naïve Bayes classifier, distance metrics, partitioning clustering, associate mining, data marts and operational data store are discussed comprehensively',
     "publish_date": "2019-10-03", "num_reviews": 75, "publisher": "Cambridge"},
    {"title": "Mining the Social Web", "authors": ["Matthew A. Russell", "Mikhail Klassen"],
     "summary": 'Learn how to employ best-in-class Python 3 tools to slice and dice the data you collect Apply advanced mining techniques such as TFIDF, cosine similarity, collocation analysis, clique detection, and image recognition',
     "publish_date": "2017-10-03", "num_reviews": 25, "publisher": "oreilly"},
    {"title": "Big Data Analytics Methods", "authors": ["Peter Ghavami"],
     "summary": 'Analytics Techniques in Data Mining, Deep Learning and Natural Language Processing',
     "publish_date": "2019-11-23", "num_reviews": 29, "publisher": "manning"},
    {"title": "Data Analytics For Businesses", "authors": ["Edward Brown"],
     "summary": 'How to Master Data Science with Optimized Marketing Strategies using Data Mining Algorithms, Big Data for Business and Machine Learning',
     "publish_date": "2019-11-23", "num_reviews": 69, "publisher": "manning"},
    {"title": "The Pragmatic Programmer", "authors": ["Andy Hunt", "Dave Thomas"],
     "summary": 'this book is essential for software developers who want to develop their skills and become masters of the field',
     "publish_date": "2019-11-23", "num_reviews": 79, "publisher": "manning"},
    {"title": "Head First Statistics: A Brain-Friendly Guide", "authors": ["Andy Hunt"],
     "summary": 'The book covers a lot of statistics starting with descriptive statistics – mean, median, mode, standard deviation – and then go on to probability and inferential statistics like correlation, regression',
     "publish_date": "2019-11-23", "num_reviews": 79, "publisher": "oreilly"},
    {"title": "Practical Statistics for Data Scientists", "authors": ["Peter Bruce"],
     "summary": 'this book will give you a good overview of all the concepts that you need to learn to master data science',
     "publish_date": "2018-11-23", "num_reviews": 19, "publisher": "oreilly"},
    {"title": "Introduction to Probability", "authors": ["Jessica Hawng"],
     "summary": 'This is perhaps the best book to learn about probability. The explanations are pretty neat and resemble real-life problems. If you have studied probability in school, this book is a must-have to further your knowledge of the basic concepts.',
     "publish_date": "2019-11-23", "num_reviews": 59, "publisher": "CRC Press"},
    {"title": "Introduction to Machine Learning with Python", "authors": ["Andreas Muller"],
     "summary": 'This is a book that can get you kick-started on your ML journey with Python. The concepts are explained as if to a layman and with sufficient examples for a better understanding. The tone is friendly and easy to understand. ML is quite a complex topic, however, after practicing along with the book, you should be able to build your own ML models. You will get a good grasp of ML concepts. The book has examples in Python but you wouldn’t need any prior knowledge of either maths or Programming languages for reading this book',
     "publish_date": "2018-11-23", "num_reviews": 33, "publisher": "oreilly"},
    {"title": "Python Machine Learning By Example", "authors": ["Yuxi Liu"],
     "summary": 'The book gets you started with Python and machine learning in a detailed and interesting way with some classy examples like the spam email detection using Bayes and predictions using regression and tree-based algorithms. The author shares his experiences in the various areas of ML such as ad optimization, conversion rate prediction, click fraud detection, etc. which beautifully adds to the reading experience',
     "publish_date": "2018-11-23", "num_reviews": 45, "publisher": "packt"},
    {"title": "Pattern recognition and machine learning", "authors": ["Christopher Bishop"],
     "summary": 'this is one book that covers machine learning inside out. It is thorough and explains the concepts with examples in a simple way. Few readers could find some of the terms tough to understand but you should be able to get through using other free resources like web articles or videos. The book is a must-have if you are serious about getting into machine learning, especially the mathematical (data analytics) part is exhaustive in nature',
     "publish_date": "2012-11-23", "num_reviews": 159, "publisher": "manning"},
    {"title": "Python for data analysis", "authors": ["Wes McKinney"],
     "summary": 'It is a great start for a beginner and covers basics about Python before moving on to Python’s role in data analysis and statistics. The book is fast-paced and explains everything in a super simple manner. You can build some real applications within a week of reading the book. This book can also give you a guideline or be a reference for the topics that you will be otherwise lost for when you search for online courses',
     "publish_date": "2017-11-23", "num_reviews": 259, "publisher": "oreilly"},
     {"title": "Naked statistics", "authors": ["Charles Wheelan"],
     "summary": 'This book brings out the beauty of statistics and makes statistics come alive. The tone is witty and conversational. You will not get bored reading this book or feel the heaviness of math! The author explains all the concepts of statistics – basic and advanced with real-life examples. The book starts with very basic stuff like the normal distribution, central theorem and goes on to complex real-life problems and correlating data analysis and machine learning',
     "publish_date": "2019-11-23", "num_reviews": 22, "publisher": "oreilly"},
    {"title": "Data Science and big data analytics", "authors": ["Charles Wheelan"],
     "summary": 'his book gently introduces big data and how it is important in today’s digitally competitive world. The whole data analytics lifecycle is explained in detail along with case study and appealing visuals so that you can see the practical working of the entire system. The structure and flow of the book are very good and well organized. You can easily understand the entire big picture of how analytics is done as each step is like one chapter in the book. The book includes clustering, regression, association rules and much more along with simple, everyday examples that one can relate to. Advanced analytics using MapReduce, Hadoop, and SQL are also introduced to the reader',
     "publish_date": "2019-11-23", "num_reviews": 222, "publisher": "manning"},
    {"title": "R for data science", "authors": ["Garret Grolemund"],
     "summary": 'Another book for beginners who want to learn data science using R. R with data science explains not just the concepts of statistics but also the kind of data you would see in real life, how to transform it using the concepts like median, average, standard deviation etc. and how to plot the data, filter and clean it. The book will help you understand how messy and raw real data is and how it is processed. Transformation of data is one of the most time-consuming tasks and this book will help you gain a lot of knowledge on different methods of transforming data for processing so that meaningful insights can be taken from it',
     "publish_date": "2019-01-23", "num_reviews": 12, "publisher": "oreilly"},
    {"title": "The Data Warehouse Toolkit", "authors": ["Ralph Kimball"],
     "summary": 'is a complete library of updated dimensional modeling techniques, the most comprehensive collection ever. It covers new and enhanced star schema dimensional modeling patterns, adds two new chapters on ETL techniques, includes new and expanded business matrices for 12 case studies, and more. Design dimensional databases that are easy to understand and provide fast query response with this book',
     "publish_date": "2016-01-23", "num_reviews": 12, "publisher": "oreilly"},
    {"title": "Agile Data Warehouse Design", "authors": ["Garret Grolemund"],
     "summary": 'The book describes BEAM, an agile approach to dimensional modeling, for improving communication between data warehouse designers, BI stakeholders and the whole DW/BI development team. BEAM provides tools and techniques that will encourage DW/BI designers and developers to move away from their keyboards and entity relationship based tools and model interactively with their colleagues. Developers understand how to efficiently implement dimensional modeling solutions. Business stakeholders feel ownership of the data warehouse they have created, and can already imagine how they will use it to answer their business questions.Collaborative Dimensional Modeling, from Whiteboard to Star Schema',
     "publish_date": "2019-01-23", "num_reviews": 12, "publisher": "CRC Press"},
    {"title": "Database Systems: Introduction to Databases and Data Warehouses", "authors": ["Garret Grolemund"],
     "summary": 'Designed for use in undergraduate and graduate information systems database courses, this is an introductory yet comprehensive text that requires no prerequisites. Its goal is to provide a significant level of database expertise to students. Students will learn to design and use operational and analytical databases and will be prepared to apply their knowledge in today’s business environments. The book’s website includes access to the free Web-based data modelling suite ERDPlus designed and developed in conjunction with the text. Students and instructors can use ERDPlus to create ER diagrams, relational schemas, and dimensional models.',
     "publish_date": "2016-01-23", "num_reviews": 128, "publisher": "manning"},
    {"title": "Building a Scalable Data Warehouse with Data Vault 2.0", "authors": ["Paul Newmann"],
     "summary": 'The Data Vault was invented by Dan Linstedt at the U.S. Department of Defense. Building a Scalable Data Warehouse covers everything one needs to know to create a scalable data warehouse end to end, including a presentation of the Data Vault modeling technique, which provides the foundations to create a technical data warehouse layer. The book discusses how to build the data warehouse incrementally using the agile Data Vault 2.0 methodology. In addition, readers will learn how to create the input layer (the stage layer) and the presentation layer (data mart) of the Data Vault 2.0 architecture including implementation best practices.',
     "publish_date": "2016-01-23", "num_reviews": 128, "publisher": "emc"},
    {"title": "Data Warehousing Fundamentals for IT Professionals", "authors": ["Paul Skinner"],
     "summary": 'This practical Second Edition highlights the areas of data warehousing and business intelligence where high-impact technological progress has been made. Discussions on developments include data marts, real-time information delivery, data visualization, requirements gathering methods, multi-tier architecture, OLAP applications, Web clickstream analysis, data warehouse appliances, and data mining techniques. The book also contains review questions and exercises for each chapter, appropriate for self-study or classroom work, industry examples of real-world situations, and several appendices with valuable information',
     "publish_date": "2016-01-23", "num_reviews": 328, "publisher": "emc"},
    {"title": "The Kimball Group Reader: Relentlessly Practical for Data Warehousing and Business Intelligence Remastered Collection", "authors": ["Paul Kimball"],
     "summary": 'The Kimball Group Reader, Remastered Collection is the essential reference for data warehouse and business intelligence design, packed with best practices, design tips, and valuable insight from industry pioneer Ralph Kimball and the Kimball Group. This Remastered Collection represents decades of expert advice and mentoring in data warehousing and business intelligence, and is the final work to be published by the Kimball Group. Organized for quick navigation and easy reference, this book contains nearly 20 years of experience on more than 300 topics, all fully up-to-date and expanded with 65 new articles',
     "publish_date": "2016-11-21", "num_reviews": 344, "publisher": "manning"},
    {"title": "Agile Data Warehousing for the Enterprise: A Guide for Solution Architects and Project Leaders", "authors": ["Paul Kimball"],
     "summary": 'Building upon his earlier book that detailed agile data warehousing programming techniques for the Scrum master, the author’s latest work illustrates the agile interpretations of the remaining software engineering disciplines. Use this step-by-step guide to deepen your own application development skills through self-study, show your teammates the world’s fastest and most reliable techniques for creating business intelligence systems, or ensure that the IT department working for you is building your next decision support system the right way.',
     "publish_date": "2016-11-21", "num_reviews": 344, "publisher": "manning"},
    {"title": "Building a Data Warehouse", "authors": ["Paul Lancombe"],
     "summary": 'Here is the ideal field guide for data warehousing implementation. This book first teaches you how to build a data warehouse, including defining the architecture, understanding the methodology, gathering the requirements, designing the data models, and creating the databases. Coverage then explains how to populate the data warehouse and explores how to present data to users using reports and multidimensional databases and how to use the data in the data warehouse for business intelligence, customer relationship management, and other purposes. It also details testing and how to administer data warehouse operation.',
     "publish_date": "2016-11-21", "num_reviews": 52, "publisher": "oreilly"},
    {"title": "Agile Analytics", "authors": ["Sarah Langard"],
     "summary": 'A Value-Driven Approach to Business Intelligence and Data Warehousing',
     "publish_date": "2014-11-21", "num_reviews": 552, "publisher": "oreilly"},
    {"title": "Hadoop: The Definitive Guide: Storage and Analysis at Internet Scale", "authors": ["Sarah Langard"],
     "summary": 'Get ready to unlock the power of your data. With the fourth edition of this comprehensive guide, you’ll learn how to build and maintain reliable, scalable, distributed systems with Apache Hadoop. This book is ideal for programmers looking to analyze datasets of any size, and for administrators who want to set up and run Hadoop clusters. Using Hadoop 2 exclusively, author Tom White presents new chapters on YARN and several Hadoop-related projects such as Parquet, Flume, Crunch, and Spark. You’ll learn about recent changes to Hadoop, and explore new case studies on Hadoop’s role in healthcare systems and genomics data processing',
     "publish_date": "2014-11-21", "num_reviews": 552, "publisher": "oreilly"},
    {"title": "Big Data: Principles and best practices of scalable realtime data systems", "authors": ["Garret Grolemund"],
     "summary": 'Big Data teaches you to build big data systems using an architecture designed specifically to capture and analyze web-scale data. This book presents the Lambda Architecture, a scalable, easy-to-understand approach that can be built and run by a small team. You’ll explore the theory of big data systems and how to implement them in practice. In addition to discovering a general framework for processing big data, you’ll learn specific technologies like Hadoop, Storm, and NoSQL databases. This book requires no previous exposure to large-scale data analysis or NoSQL tools. Familiarity with traditional databases is helpful.',
     "publish_date": "2017-11-21", "num_reviews": 552, "publisher": "oreilly"},
    {"title": "Designing Data-Intensive Applications", "authors": ["Garret Grolemund"],
     "summary": 'Data is at the center of many challenges in system design today. Difficult issues need to be figured out, such as scalability, consistency, reliability, efficiency, and maintainability. In this practical and comprehensive guide, author Martin Kleppmann helps you navigate this diverse landscape by examining the pros and cons of various technologies for processing and storing data. Software keeps changing, but the fundamental principles remain the same. With this book, software engineers and architects will learn how to apply those ideas in practice, and how to make full use of data in modern applications.',
     "publish_date": "2017-11-21", "num_reviews": 552, "publisher": "oreilly"},
]


if __name__ == "__main__":
    elk = ElasticBookStorage()
    elk.create_book_index()

    elk.bulk_insert(data=DATA)


